import type { Survey } from "../types";
import {
  addressQuestion,
  budgetQuestion,
  contactQuestion,
  finishQuestion,
  opt,
  ownerQuestion,
  sizeQuestion,
  timelineQuestion,
} from "./shared";

export const bathroomRenovation: Survey = {
  id: "bathroomRenovation",
  label: "Bathroom Renovation",
  description: "Renovate your bathroom into a functional, modern space.",
  questions: [
    {
      id: "bathroomType",
      type: "single",
      title: "What type of bathroom renovation are you planning?",
      subText: "Select the scope of your renovation project.",
      ghlFieldKey: "bathroomType",
      required: true,
      options: opt([
        "Complete Bathroom Renovation",
        "Partial Bathroom Renovation",
      ]),
    },
    {
      id: "renovationReason",
      type: "single",
      title: "Why are you renovating your bathroom?",
      subText: "Choose the primary reason for your renovation.",
      ghlFieldKey: "renovationReason",
      required: true,
      options: opt([
        "Improve Resale Value",
        "Need More Space",
        "Improve the Look and Functionality",
        "Modernize an Outdated Bathroom",
      ]),
    },
    sizeQuestion({
      title: "What is the approximate size of your bathroom?",
      subText: "Provide an approximate size to help us estimate project scope and cost.",
      guide: [
        { label: "Powder Room", value: "2 - 4 sqm" },
        { label: "Standard Bathroom", value: "5 - 8 sqm" },
        { label: "Family Bathroom", value: "8 - 12 sqm" },
        { label: "Master Ensuite", value: "10 - 15 sqm" },
        { label: "Large Luxury Bathroom", value: "15+ sqm" },
      ],
    }),
    {
      id: "bathroomCount",
      type: "single",
      title: "How many bathrooms are included in this renovation?",
      subText: "Select the number of bathrooms being renovated.",
      ghlFieldKey: "bathroomCount",
      required: true,
      options: opt(["1 Bathroom", "2 Bathrooms", "3 Bathrooms", "4+ Bathrooms"]),
    },
    {
      id: "improvements",
      type: "multi",
      title: "What improvements are you looking for?",
      subText: "Select all improvements you would like included in your renovation.",
      ghlFieldKey: "improvements",
      required: true,
      options: opt([
        "Updated Fixtures",
        "Additional Space",
        "Different Layout",
        "New Shower",
        "New Bathtub",
        "Double Vanity",
        "Improved Storage",
        "Better Accessibility",
      ]),
    },
    {
      id: "layoutPreference",
      type: "single",
      title: "Do you plan to keep the existing layout?",
      subText: "Layout changes may impact plumbing, electrical work, and project costs.",
      ghlFieldKey: "layoutPreference",
      required: true,
      options: opt(["Same Layout", "New Layout"]),
    },
    {
      id: "manageDuringReno",
      type: "single",
      title: "How do you plan to manage during the renovation?",
      subText: "Let us know what arrangements you have while the bathroom is unavailable.",
      ghlFieldKey: "manageDuringReno",
      required: true,
      options: opt([
        "I Have Alternative Accommodation",
        "I Have Another Bathroom Available",
        "I Need a Portable Ensuite",
        "Not Sure Yet",
      ]),
    },
    {
      id: "professionalDesigns",
      type: "single",
      title: "Do you already have professional designs or drawings?",
      subText: "This helps us understand how far along you are in the planning process.",
      ghlFieldKey: "professionalDesigns",
      required: true,
      options: opt(["Yes", "No"]),
    },
    finishQuestion,
    ownerQuestion,
    budgetQuestion([
      "Under $15,000",
      "$15,000 - $25,000",
      "$25,000 - $40,000",
      "$40,000 - $60,000",
      "$60,000+",
    ]),
    {
      ...timelineQuestion,
      title: "When would you like your renovation completed?",
    },
    contactQuestion,
    addressQuestion(
      "What is the location of your property?",
      "Provide the address of the property being renovated."
    ),
  ],
};
