import type { Survey } from "../types";
import {
  addressQuestion,
  budgetQuestion,
  contactQuestion,
  designerQuestion,
  finishQuestion,
  financingQuestion,
  opt,
  ownerQuestion,
  plansQuestion,
  sizeQuestion,
  timelineQuestion,
} from "./shared";

export const customHome: Survey = {
  id: "customHome",
  label: "Custom Home",
  description: "Build a brand-new home from the ground up.",
  questions: [
    {
      id: "homeType",
      type: "single",
      title: "What type of home would you like to build?",
      subText: "Choose the style of home you're planning.",
      ghlFieldKey: "homeType",
      required: true,
      options: opt(["Apartment", "Single Storey Home", "Multi Storey Home"]),
    },
    {
      id: "landStatus",
      type: "single",
      title: "Do you already have the land?",
      subText: "This significantly affects your total project cost.",
      ghlFieldKey: "landStatus",
      required: true,
      options: opt([
        "I own the land",
        "Buying land",
        "Knockdown-rebuild",
        "Not yet",
      ]),
    },
    {
      id: "bedrooms",
      type: "single",
      title: "How many bedrooms would you like?",
      subText: "Select the number of bedrooms required.",
      ghlFieldKey: "bedrooms",
      required: true,
      options: opt([
        "1 Bedroom",
        "2 Bedrooms",
        "3 Bedrooms",
        "4 Bedrooms",
        "5 Bedrooms",
      ]),
    },
    {
      id: "bathrooms",
      type: "single",
      title: "How many bathrooms do you need?",
      subText: "Select the number of bathrooms required.",
      ghlFieldKey: "bathrooms",
      required: true,
      options: opt([
        "1 Bathroom",
        "2 Bathrooms",
        "3 Bathrooms",
        "4 Bathrooms",
        "5 Bathrooms",
      ]),
    },
    {
      id: "livingAreas",
      type: "single",
      title: "How many living or dining areas would you like?",
      subText: "This helps us understand your lifestyle and space requirements.",
      ghlFieldKey: "livingAreas",
      required: true,
      options: opt(["1 Area", "2 Areas", "3 Areas", "4 Areas"]),
    },
    {
      id: "carSpaces",
      type: "single",
      title: "How many car spaces would you like?",
      subText: "Let us know your garage or carport needs.",
      ghlFieldKey: "carSpaces",
      required: true,
      options: opt(["None", "Single", "Double", "Triple+"]),
    },
    sizeQuestion({
      title: "What size of home are you looking to build?",
      subText: "Provide the approximate size of your new home.",
      guide: [
        { label: "Compact", value: "50 - 120 sqm" },
        { label: "Moderate", value: "120 - 180 sqm" },
        { label: "Spacious", value: "180 - 250 sqm" },
        { label: "Grand", value: "250 - 350 sqm" },
        { label: "Luxury", value: "350+ sqm" },
      ],
    }),
    finishQuestion,
    designerQuestion,
    plansQuestion,
    financingQuestion,
    budgetQuestion([
      "$250,000 - $400,000",
      "$400,000 - $600,000",
      "$600,000 - $800,000",
      "$800,000 - $1,000,000",
      "$1,000,000+",
    ]),
    timelineQuestion,
    {
      ...ownerQuestion,
      title: "Are you the property owner or authorized decision maker?",
    },
    addressQuestion(
      "Where do you intend to build your new home?",
      "Provide the location of your future build."
    ),
    contactQuestion,
  ],
};
