import type { Survey } from "../types";
import {
  addressQuestion,
  budgetQuestion,
  contactQuestion,
  finishQuestion,
  opt,
  ownerQuestion,
  sizeQuestion,
  timelineQuestion,
} from "./shared";

export const kitchenRenovation: Survey = {
  id: "kitchenRenovation",
  label: "Kitchen Renovation",
  description: "Transform your kitchen with a full or partial remodel.",
  questions: [
    {
      id: "kitchenScope",
      type: "single",
      title: "What is the scope of your kitchen renovation?",
      subText: "Are you planning a complete remodel or upgrading specific areas?",
      ghlFieldKey: "kitchenScope",
      required: true,
      options: opt(["Complete Kitchen Remodel", "Partial Kitchen Remodel"]),
    },
    {
      id: "kitchenLayout",
      type: "single",
      title: "What is the current layout of your kitchen?",
      subText: "This helps us understand your existing space and design possibilities.",
      ghlFieldKey: "kitchenLayout",
      required: true,
      options: opt([
        "Single Wall",
        "L-Shaped",
        "Galley",
        "U-Shaped",
        "G-Shaped",
        "Other",
      ]),
    },
    {
      id: "kitchenIsland",
      type: "single",
      title: "Do you have or want a kitchen island?",
      subText: "Knowing your layout helps us assess renovation opportunities.",
      ghlFieldKey: "kitchenIsland",
      required: true,
      options: opt([
        "Have one & keeping it",
        "Want to add one",
        "Don't want one",
      ]),
    },
    sizeQuestion({
      title: "What size is your kitchen?",
      subText: "Provide an approximate size to help us estimate project scope and cost.",
      guide: [
        { label: "Small Kitchen", value: "8 - 12 sqm" },
        { label: "Medium Kitchen", value: "12 - 20 sqm" },
        { label: "Large Kitchen", value: "20 - 30 sqm" },
        { label: "Open Plan Kitchen", value: "30+ sqm" },
      ],
    }),
    {
      id: "areasToUpdate",
      type: "multi",
      title: "Which areas are you planning to update?",
      subText: "Select all areas included in your renovation.",
      ghlFieldKey: "areasToUpdate",
      required: true,
      options: opt([
        "Cabinets",
        "Appliances",
        "Countertops",
        "Faucets & Sinks",
        "Splashback",
        "Flooring",
        "Lighting",
      ]),
    },
    {
      id: "countertopMaterial",
      type: "single",
      title: "What is your preferred countertop material?",
      subText: "Select your preferred countertop material if known.",
      ghlFieldKey: "countertopMaterial",
      required: true,
      options: opt([
        "Engineered Quartz",
        "Granite",
        "Laminate",
        "Porcelain",
        "Not Sure",
      ]),
    },
    {
      id: "splashbackMaterial",
      type: "single",
      title: "What is your preferred splashback material?",
      subText: "Select your preferred splashback material if known.",
      ghlFieldKey: "splashbackMaterial",
      required: true,
      options: opt([
        "Tile",
        "Glass",
        "Engineered Quartz",
        "Granite",
        "Porcelain",
        "Not Sure",
      ]),
    },
    {
      id: "flooringMaterial",
      type: "single",
      title: "What is your preferred flooring material?",
      subText: "Select your preferred flooring material if known.",
      ghlFieldKey: "flooringMaterial",
      required: true,
      options: opt([
        "Tile",
        "Vinyl Plank",
        "Vinyl Hybrid",
        "Hardwood",
        "Not Sure",
      ]),
    },
    {
      id: "servicesRelocate",
      type: "multi",
      title: "Do any of the following services need to be relocated?",
      subText: "Relocating services affects project complexity and cost.",
      ghlFieldKey: "servicesRelocate",
      required: true,
      options: opt(["Plumbing", "Electrical", "Gas Line", "None Required"]),
    },
    finishQuestion,
    budgetQuestion([
      "Under $20,000",
      "$20,000 - $35,000",
      "$35,000 - $55,000",
      "$55,000 - $80,000",
      "$80,000+",
    ]),
    {
      ...ownerQuestion,
      title: "Are you the property owner or authorized to approve changes?",
    },
    {
      ...timelineQuestion,
      title: "When would you like your renovation completed?",
    },
    contactQuestion,
    addressQuestion(
      "Where is your property located?",
      "Provide the address of the property being renovated."
    ),
  ],
};
